name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Cloud Foundry CLI
      - name: Install Cloud Foundry CLI
        run: |
          # Download CF CLI tarball from GitHub release
          curl -L -o cf-cli.tgz https://github.com/cloudfoundry/cli/releases/download/v8.4.0/cf8-cli_8.4.0_linux-x86-64.tgz
          # Extract tarball
          mkdir cf-cli
          tar -xvzf cf-cli.tgz -C cf-cli
          # Move cf executable to /usr/local/bin
          sudo mv cf-cli/cf /usr/local/bin/cf
          # Verify installation
          cf version

      # Step 3: Deploy to Cloud Foundry
      - name: Deploy to Cloud Foundry
        env:
          CF_API: https://api.cf.us10-001.hana.ondemand.com
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: 7e62d5b9trial
          CF_SPACE: dev
        run: |
          # Set API endpoint
          cf api $CF_API
          # Authenticate
          cf auth $CF_USERNAME $CF_PASSWORD
          # Target the org and space
          cf target -o $CF_ORG -s $CF_SPACE
          # Push the app
          cf push warehouse-tracker --no-cache
