name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cloud Foundry CLI
        run: |
          # Download official CF CLI install script
          curl -L https://packages.cloudfoundry.org/stable?release=linux64&source=github -o cf-install.sh
          chmod +x cf-install.sh
          sudo ./cf-install.sh
          cf version

      - name: Deploy to Cloud Foundry
        env:
          CF_API: https://api.cf.us10-001.hana.ondemand.com
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: 7e62d5b9trial
          CF_SPACE: dev
        run: |
          cf api $CF_API
          cf auth $CF_USERNAME $CF_PASSWORD
          cf target -o $CF_ORG -s $CF_SPACE
          cf push warehouse-tracker --no-cache
