name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud Foundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable/cloudfoundry-cli_8.0.0_linux_x86-64.tgz" -o cf-cli.tgz
          mkdir cf-cli
          tar -xvzf cf-cli.tgz -C cf-cli
          sudo mv cf-cli/cf /usr/local/bin/cf

      - name: Deploy to Cloud Foundry
        env:
          CF_API: https://api.cf.us10-001.hana.ondemand.com
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: 7e62d5b9trial
          CF_SPACE: dev
        run: |
          cf api $CF_API
          cf auth "$CF_USERNAME" "$CF_PASSWORD"
          cf target -o "$CF_ORG" -s "$CF_SPACE"
          cf push --no-cache
