name: Deploy to Cloud Foundry

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Cloud Foundry CLI
      - name: Install Cloud Foundry CLI
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" -o cf-install.sh
          chmod +x cf-install.sh
          ./cf-install.sh
          cf version

      # Step 3: Deploy your app to Cloud Foundry
      - name: Deploy to Cloud Foundry
        env:
          CF_API: https://api.cf.us10-001.hana.ondemand.com
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: 7e62d5b9trial
          CF_SPACE: dev
        run: |
          cf api $CF_API
          cf auth $CF_USERNAME $CF_PASSWORD
          cf target -o $CF_ORG -s $CF_SPACE
          cf push warehouse-tracker --no-cache
