name: Deploy to Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Cloud Foundry and deploy
      - name: Deploy to Cloud Foundry
        uses: cloudfoundry/cf-action@v1
        with:
          api: https://api.cf.us10-001.hana.ondemand.com
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          org: 7e62d5b9trial
          space: dev
          command: push warehouse-tracker --no-cache
