name: Deploy to SAP Cloud Foundry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Cloud Foundry CLI using official installer
      - name: Install Cloud Foundry CLI
        run: |
          wget -q -O cf-install.sh "https://packages.cloudfoundry.org/stable?release=linux64&source=github"
          chmod +x cf-install.sh
          sudo ./cf-install.sh
          cf version

      # Step 3: Deploy your app to SAP CF
      - name: Deploy app to SAP CF
        env:
          CF_API: https://api.cf.us10-001.hana.ondemand.com
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: 7e62d5b9trial
          CF_SPACE: dev
        run: |
          # Target SAP CF
          cf api $CF_API
          cf auth "$CF_USERNAME" "$CF_PASSWORD"
          cf target -o "$CF_ORG" -s "$CF_SPACE"

          # Push your app
          cf push warehouse-tracker --no-cache
